### ISSUE TITLE
Docs still not deploying

### ISSUE THREAD

**Issue by alecloudenback** [JuliaFinance/DayCounts.jl#13]
https://github.com/JuliaFinance/DayCounts.jl/runs/614217696

**Comment by felipenoris** [comment]
I can take a look at this for you, but the reason is this:

```
┌ Info: Deployment criteria:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="" occurs in repo="github.com/JuliaFinance/DayCounts.jl.git"
│ - ✘ ENV["TRAVIS_PULL_REQUEST"]="" is "false"
│ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
│ - ✘ ENV["TRAVIS_BRANCH"]="" matches devbranch="master (if tag is empty)
│ - ✘ ENV["DOCUMENTER_KEY"] exists
└ Deploying: ✘
```

**Comment by alecloudenback** [comment]
Yea, the issue was a reminder for me - I haven't been able to figure out where those TRAVIS env variable are set though? I set up CI via Github Actions in the JuliaActuary and didn't need to set those up. I'm assuming it's something that I need to undo but can't find where to undo it

I set up the DOCUMENTER_KEY:

![image](https://user-images.githubusercontent.com/711879/80268595-0369a080-866e-11ea-915e-30c2fbcf4e12.png)

**Comment by felipenoris** [comment]
There you go.
2f20d22b18190942f90125650e6de8cf2aa9ad60
