### ISSUE TITLE
Remove Manifest?

### ISSUE THREAD

**Issue by felipenoris** [JuliaFinance/DayCounts.jl#3]
Since this is a library and not a runnable project, should Manifest file be deleted?

**Comment by simonbyrne** [comment]
It doesn't really matter: if used as part of another project it is ignored. The main argument for keeping it is that it lets you edit the package as a project (i.e. you can set `--project=<pkgdir>`).

**Comment by felipenoris** [comment]
Oh, good to know. Thanks!
